version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: arual
      MYSQL_DATABASE: crypto_db
      MYSQL_USER: root
      MYSQL_PASSWORD: arual
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crypto_net

  api:
    build: ./api
    container_name: crypto_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - crypto_net

volumes:
  db_data:

networks:
  crypto_net:
